# 安装实际是升级

#
# skv_offline
#

# 把zkconf从sp拷贝到skv
offline_copy_zk_conf:
  step_type: step
  agent_name: sa_cluster
  hosts: execute

# 替换meta server: 逐一停/起
offline_replace_meta_server:
  step_type: step
  agent_name: sa_cluster
  hosts: execute

# 替换replica server: 逐一停/起
offline_replace_replica_server:
  step_type: step
  agent_name: sa_cluster
  hosts: execute
  timeout: 1800  # 可能会很久

#
# skv_online
#

# 把zkconf从sp拷贝到skv
online_copy_zk_conf:
  step_type: step
  agent_name: sa_cluster
  hosts: execute

# 替换meta server: 逐一停/起
online_replace_meta_server:
  step_type: step
  agent_name: sa_cluster
  hosts: execute

# 替换replica server: 逐一停/起
online_replace_replica_server:
  step_type: step
  agent_name: sa_cluster
  hosts: execute
  timeout: 1800  # 可能会很久


# 清理最后清理
cleanup:
  step_type: step
  agent_name: sa_cluster
  hosts: execute
  timeout: 1800 # 可能会很久
