# 检查服务是否启动 没有流量 并且备份目录为空
pre_check:
  class_name: PreCheckStep
  hosts: execute

# 写入测试表
static_data:
  class_name: StaticDataStep
  hosts: execute

# 检查磁盘空间够不够
make_snapshot:
  class_name: MakeSnapshotStep
  hosts: all
  # 有du -sm操作 超时长一些
  timeout: 3600

# 一个标记位
# 这里感觉是bug 如果第一次to_step是pre_check并且成功执行完毕 下一次to_step是最后一步 实际上会从pre_check继续执行
# 但是云平台那边应该不会处理这类问题了 因此我这里绕一下
snapshot_done:
  class_name: SnapshotDoneStep
  hosts: execute

# 备份当前zk节点到一个json文件中去 
backup_zk:
  class_name: BackupZkStep
  hosts: execute

# 对replica server的数据目录打包
tar_replica_data:
  class_name: TarReplicaDataStep
  hosts: all
  # 有tar和md5操作 超时长一些
  timeout: 7200

# 计算新节点数据分布拓扑以及老节点数据迁移路径
calculate_new_replica_map:
  class_name: CalculateNewReplicaMapStep
  hosts: execute

# 根据数据转移路径生成发送数据的 scp 脚本
generate_replica_migrate_path:
  class_name: GenerateReplicaMigratePathStep
  hosts: all

# 恢复checkpoint目录 用于后续自动清理掉
cleanup:
  class_name: CleanupStep
  hosts: all
