core|data_dir:
  tag: ''
  desc: ''
  type: str
core|log_dir:
  tag: ''
  desc: ''
  type: str
network|explicit_host_address:
  tag: ''
  desc: ''
  type: str
pegasus.server|rocksdb_total_size_across_write_buffer:
  tag: ''
  desc: ''
  type: int
pegasus.server|perf_counter_cluster_name:
  tag: ''
  desc: ''
  type: str
pegasus.server|prometheus_host:
  tag: ''
  desc: ''
  type: str
pegasus.server|prometheus_port:
  tag: ''
  desc: ''
  type: str
replication|data_dirs:
  tag: ''
  desc: ''
  type: str
replication|data_dirs_black_list_file:
  tag: ''
  desc: ''
  type: str
replication|slog_dir:
  tag: ''
  desc: ''
  type: str
replication|cluster_name:
  tag: ''
  desc: ''
  type: str
replication|mutation_2pc_min_replica_count:
  tag: ''
  desc: ''
  type: int
replication.app|max_replica_count:
  tag: ''
  desc: ''
  type: int
replication.app|partition_count:
  tag: ''
  desc: ''
  type: int
