core|data_dir:
  tag: ''
  desc: ''
  type: str
core|log_dir:
  tag: ''
  desc: ''
  type: str
meta_server|max_allowed_replica_count:
  tag: ''
  desc: ''
  type: int
meta_server|server_list:
  tag: ''
  desc: ''
  type: str
meta_server|cluster_root:
  tag: ''
  desc: ''
  type: str
meta_server|distributed_lock_service_parameters:
  tag: ''
  desc: ''
  type: str
meta_server|min_live_node_count_for_unfreeze:
  tag: ''
  desc: ''
  type: int
meta_server.apps.__detect|max_replica_count:
  tag: ''
  desc: ''
  type: int
meta_server.apps.__detect|partition_count:
  tag: ''
  desc: ''
  type: int
meta_server.apps.__stat|max_replica_count:
  tag: ''
  desc: ''
  type: int
meta_server.apps.__stat|partition_count:
  tag: ''
  desc: ''
  type: int
network|explicit_host_address:
  tag: ''
  desc: ''
  type: str
pegasus.clusters|skv_offline:
  tag: ''
  desc: ''
  type: str
pegasus.server|perf_counter_cluster_name:
  tag: ''
  desc: ''
  type: str
pegasus.server|prometheus_host:
  tag: ''
  desc: ''
  type: str
pegasus.server|prometheus_port:
  tag: ''
  desc: ''
  type: str
replication.app|max_replica_count:
  tag: ''
  desc: ''
  type: int
replication.app|partition_count:
  tag: ''
  desc: ''
  type: int
zookeeper|hosts_list:
  tag: ''
  desc: ''
  type: str
zookeeper|wrapper_log_dir:
  tag: ''
  desc: ''
  type: str
zookeeper|helper_log_dir:
  tag: ''
  desc: ''
  type: str
